apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.orgName }}-{{ .Values.global.component }}-shared
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
