apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.orgName }}-{{ .Values.global.component }}-envvar
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CA_USER: {{ .Values.config.ca.caUser }}
  CA_PASSWORD: {{ .Values.config.ca.caPassword }}
